CREATE TABLE tareas
(
    tare_id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tare_title     VARCHAR(255),
    tare_completed BOOLEAN,
    tare_userId    INTEGER,
    CONSTRAINT pk_tareas PRIMARY KEY (tare_id)
);

