CREATE TABLE clientes
(
    clie_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    clie_cedula VARCHAR(255),
    clie_email  VARCHAR(255),
    CONSTRAINT pk_clientes PRIMARY KEY (clie_id)
);