CREATE TABLE prestamos
(
    pres_id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pres_clienteId   INTEGER,
    pres_tasaInteres FLOAT,
    pres_montoTotal  FLOAT,
    CONSTRAINT pk_prestamos PRIMARY KEY (pres_id)
);

CREATE TABLE pagos
(
    pago_id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pago_montoPago   FLOAT,
    pago_fechaPago   TIMESTAMP WITHOUT TIME ZONE,
    pago_prestamo_id INTEGER,
    CONSTRAINT pk_pagos PRIMARY KEY (pago_id)
);

ALTER TABLE pagos
    ADD CONSTRAINT FK_PAGOS_ON_PAGO_PRESTAMO FOREIGN KEY (pago_prestamo_id) REFERENCES prestamos (pres_id);