CREATE TABLE productos
(
    prod_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    prod_nombre VARCHAR(255),
    prod_precio FLOAT,
    CONSTRAINT pk_productos PRIMARY KEY (prod_id)
);

CREATE TABLE clientes
(
    clie_id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    clie_nombre    VARCHAR(255),
    clie_apellido  VARCHAR(255),
    clie_direccion VARCHAR(255),
    CONSTRAINT pk_clientes PRIMARY KEY (clie_id)
);

CREATE TABLE facturas
(
    fact_id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fact_producto_id INTEGER,
    fact_precio      FLOAT,
    fact_cliente_id  INTEGER,
    CONSTRAINT pk_facturas PRIMARY KEY (fact_id)
);

ALTER TABLE facturas
    ADD CONSTRAINT FK_FACTURAS_ON_FACT_CLIENTE FOREIGN KEY (fact_cliente_id) REFERENCES clientes (clie_id);