quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/todo
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.flyway.migrate-at-start=true

#api de client
usuarios-api/mp-rest/url=https://jsonplaceholder.typicode.com/users

#docker hub
quarkus.container-image.group=johnquinatoa
quarkus.container-image.name=app-todo